name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      OXFORD_API_BASE_URL: ${{ vars.OXFORD_API_BASE_URL }}
      OXFORD_APP_ID: ${{ secrets.OXFORD_APP_ID }}
      OXFORD_APP_KEY: ${{ secrets.OXFORD_APP_KEY }}
      SPEECHMATICS_API_KEY: ${{ secrets.SPEECHMATICS_API_KEY }}
      TICKETMASTER_BASE_URL: ${{ vars.TICKETMASTER_BASE_URL }}
      TICKETMASTER_KEY: ${{ secrets.TICKETMASTER_KEY }}
      TICKETMASTER_SECRET: ${{ secrets.TICKETMASTER_SECRET }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t playwright-tests .

    - name: Run Playwright tests on Docker
      run: docker run -e OXFORD_API_BASE_URL -e OXFORD_APP_ID -e OXFORD_APP_KEY -e SPEECHMATICS_API_KEY -e TICKETMASTER_BASE_URL -e TICKETMASTER_KEY -e TICKETMASTER_SECRET playwright-tests

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30